Tencent/cloudbase-framework

packages/framework-plugin-website/src/index.ts
=> fix(website): ignore filepath

packages/framework-core/src/detect-frameworks/frameworks.ts
#27 
feat: add hexo detect
-  add new detect rules in framework
@binggg
=> feat:add hexo detect

packages/framework-core/src/detect-frameworks/frameworks.ts
#27 
- add gatsby detect 
@binggg
=> feat: add gatsby detect

README.md, doc/config.md
=> docs: add freamwork plugins docs

README.md, doc/template.md
=> docs: add template docs

doc/config.md, doc/template.md, packages/framework-core/src/config/resolve-config.ts, packages/framework-plugin-function/src/index.ts
Fixs #
- typo in ts and md
@binggg
=> fix(core): typo

packages/framework-core/package.json, packages/framework-core/src/config/resolve-config.ts
Fixs #
- solve config by toolbox
@lt5c
=> fix: solve config by toolbox

packages/framework-plugin-website/README.md, packages/framework-plugin-website/src/index.ts
=> feat(package): custom install commands

packages/cloudbase-static-builder/package.json, packages/cloudbase-static-builder/src/index.ts, packages/framework-plugin-website/src/index.ts
Feat：#45 
- support envVariables for website runtime
- support envVariables for website compile-time
@binggg
=> Website env variables

packages/framework-plugin-nuxt/README.md, packages/framework-plugin-nuxt/src/index.ts
=> nuxt-ssr 增加自定义安装命令功能

README.md
=> feat: add uni-app template

README.md
=> feat: 添加taro-starter

packages/framework-plugin-deno/assets/Dockerfile
Fixs #
- 修正 deno dockerfile, 确保在构建时就进行编译
@binggg
=> fix: 修正 deno dockerfile, 确保在构建时就进行编译

packages/framework-core/src/index.ts, packages/framework-core/src/plugin-manager/index.ts, packages/framework-core/src/plugin/index.ts, packages/framework-plugin-container/src/index.ts, packages/framework-plugin-dart/src/index.ts, packages/framework-plugin-database/src/index.ts, packages/framework-plugin-function/src/index.ts, packages/framework-plugin-node/src/index.ts, packages/framework-plugin-node/src/node-container-impl.ts, packages/framework-plugin-node/src/node-function-impl.ts, packages/framework-plugin-nuxt/src/index.ts, packages/framework-plugin-website/src/index.ts
=> feat(env): support run custom command with

packages/framework-plugin-deno/README.md, packages/framework-plugin-deno/assets/Dockerfile, packages/framework-plugin-deno/src/index.ts
Feature #
- 不推荐使用 entry 属性，但保留其能力，其默认值改为 空字符串 ""
- 改进 denon 使用方案说明，新方案能大幅度提升部署成功率
@binggg
=> refactor: 不推荐使用 entry 属性，改进 denon 使用方案

community/posts/2020-08-12-如何用云开发快速搭建实时 TodoList 应用/index.md
=> 添加文章：如何用云开发快速搭建实时 TodoList 应用

community/posts/2020-08-31-第一个Deno部署工具是如何打造的/index.md
Docs #
- 添加文章-第一个Deno部署工具是如何打造的
@binggg
=> docs: 添加文章-第一个Deno部署工具是如何打造的

community/posts/2020-07-20-如何用 Cloudbase Framework 部署一个Vue项目/index.md
docs: 添加文章-如何用 Cloudbase Framework 部署一个 Vue 项目
- 
- 
-
@binggg
=> docs: 添加文章-如何用 Cloudbase Framework 部署一个 Vue 项目

packages/framework-plugin-function/README.md
Fix https://github.com/TencentCloudBase/cloudbase-templates/pull/28
=> [fix] framework plugin inputs not work

packages/framework-plugin-deno/README.md, packages/framework-plugin-deno/assets/Dockerfile
Feature #
- denon 构建环节集成到 dockerfile
@binggg
=> denon 构建环节集成到 dockerfile

community/posts/2020-09-17-基于云开发 CloudBase 搭建在线视频会议应用/index.md
=> doc(posts): 增加文章 「基于云开发 CloudBase 搭建在线视频会议应用」

packages/framework-plugin-deno/README.md, packages/framework-plugin-deno/assets/Dockerfile, packages/framework-plugin-deno/src/builder.ts, packages/framework-plugin-deno/src/index.ts, packages/framework-plugin-deno/src/types.ts
Feature #
- deno 插件提供自动构建可选项
@binggg
=> deno 插件提供自动构建可选项

community/usercases/index.json
=> add TodoList

community/usercases/index.json
- Add Pagic as a community user case
@binggg
=> Add Pagic as a community user case

community/usercases/index.json
Fixs #91
- docs: add Twikoo to usercases
@binggg
=> docs: add Twikoo to usercases

packages/framework-plugin-next/package.json, packages/framework-plugin-next/src/index.ts
Fixs #
- create next.config.js with basePath if the file doesn't exist
@binggg
=> fix(next): create next.config.js with basePath if the file doesn't exist

community/usercases/index.json
🎉 #91
Fixs # null
添加应用案例：
- 简介：OneDrive 图床程序 ( `sosf` )
- repo 地址：[beetcb/sosf](https://github.com/beetcb/sosf)
- 特点：功能简单，但可以通过 API 扩展其能力
- 用到的云资源：个人认为 `sosf` 代码中获取和刷新 microsoft graph accesss_token 相关代码是一个比较直观和简单的云函数和数据库应用案例，故提此申请
@binggg
=> docs: add sosf to application examples

community/usercases/index.json
Fixs #91 
- docs: add Waline to usercases
@binggg
=> docs: add Waline to usercases

community/usercases/index.json
Fixs #91 
- add WorldAir to usercases
@binggg
=> docs: add WorldAir to usercases

packages/cloudbase-next-builder/src/index.ts, packages/cloudbase-nuxt-builder/src/index.ts, packages/framework-plugin-next/src/index.ts, packages/framework-plugin-nuxt/src/index.ts
✅ Closes: #156
Fixs #
- 
- 
-
@binggg
=> feat: 🎸 next、nuxt支持entry子目录build

community/usercases/index.json
Fixs #91 
-  add cloudbase-access to usercases
@binggg
=> add cloudbase-access to usercases

community/usercases/index.json
使用nuxt+tcb 云开发实现，网站没有开源。客户端是开源项目
@binggg
=> 增加巨应壁纸官网案例~

community/usercases/index.json
Fixs #
- Add Halo app example
@binggg
=> doc: add Halo app example.

.github/workflows/baseline-init.yml, scripts/local-e2e.js, scripts/online-e2e.js
=> Fix CI build eror

packages/framework-plugin-website/src/index.ts
Fixs #
静态网站托管插件添加http访问配置选项
- 
- 
-
@binggg
=> Website http

packages/framework-plugin-container/src/index.ts
=> 修正默认vpc id

packages/framework-plugin-container/src/index.ts
=> 修正云托管插件大小写错误

CONTRIBUTING.en.md
Fixs #
- 增加了CONTRIBUTING.en.md
- 
-
@binggg
=> add CONTRIBUTING.en.md

community/usercases/index.json
-  add auto build image action
=> ci(build): add auto build image action

packages/framework-plugin-function/src/index.ts
Fixs # .git files will be uploaded by default
- ignore .git
@binggg
=> feat: ignore .git

packages/cloudbase-nuxt-builder/src/index.ts
=> 变更nuxt-builder编译目标环境

scripts/build-runner/build.js, scripts/build-runner/src/Dockerfile, scripts/build-runner/src/package.json
=> chore(docker): update inner dependiencies

packages/framework-core/src/sam/index.ts, packages/framework-plugin-website/src/index.ts
Fixs #
Enable hosting in BaaS environment regardless of payment type.
@starkwang
=> feat(website): enable hosting in baas environment
